version: '3.3'
services:
  new-horizons-client-develop:
    image: 'spuxx/new-horizons-client:production-latest'
    restart: always
    networks:
      - npm

networks:
  default:
  npm:
    external: true
