name: staging

on:
  push:
    branches:
      - master

jobs:
  types:
    uses: spuxx1701/ci-cd/.github/workflows/npm_types.yml@v2.0

  lint:
    uses: spuxx1701/ci-cd/.github/workflows/npm_lint.yml@v2.0

  test:
    uses: spuxx1701/ci-cd/.github/workflows/npm_test-coverage.yml@v2.0

  release_image:
    needs:
      - types
      - lint
      - test
    uses: spuxx1701/ci-cd/.github/workflows/release_image.yml@v2.0
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  # docker_deploy:
  #   needs:
  #     - types
  #     - lint
  #     - test
  #   uses: spuxx1701/ci-cd/.github/workflows/docker_deploy.yml@v1.2
  #   with:
  #     username: spuxx
  #     repository: potber-client
  #     environment: develop
  #     dockerfile: Dockerfile.develop
  #   secrets:
  #     token: ${{ secrets.DOCKERHUB_TOKEN }}
  #     ssh_host: ${{ secrets.SSH_HOST }}
  #     ssh_username: ${{ secrets.SSH_USERNAME }}
  #     ssh_password: ${{ secrets.SSH_PASSWORD }}
